//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_POO
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedores
    {
        public int documento { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
